import React, { useEffect, useRef, useState } from 'react';
import styles from './MusicPlayer.module.css';

const audioModules = import.meta.glob('/public/audio/*.{mp3,wav,ogg,m4a}', { eager: true, query: '?url' });
// Extract the actual URL generated by Vite
const audioPaths = Object.values(audioModules).map((mod: any) => mod.default as string);
const playlist = audioPaths.length > 0 ? audioPaths : ["/audio/cinematic-placeholder.mp3"];
console.log("Audio Glob Keys:", Object.keys(audioModules));
console.log("Generated Playlist:", playlist);

interface MusicPlayerProps {
  isPlaying: boolean;
  isMuted: boolean;
  hideControls?: boolean;
  onPlayStateChange: (playing: boolean) => void;
  onMuteStateChange: (muted: boolean) => void;
}

export const MusicPlayer: React.FC<MusicPlayerProps> = ({ 
  isPlaying, 
  isMuted,
  hideControls = false,
  onPlayStateChange,
  onMuteStateChange 
}) => {
  const audioRef = useRef<HTMLAudioElement>(null);
  const [needsInteraction, setNeedsInteraction] = useState(false);
  const [trackIndex, setTrackIndex] = useState(0);

  useEffect(() => {
    const audio = audioRef.current;
    if (!audio) return;

    console.log("Attempting to play audio src:", audio.src);
    audio.muted = isMuted;

    if (isPlaying) {
      const playPromise = audio.play();
      if (playPromise !== undefined) {
        playPromise.catch((e) => {
          if (e.name === 'NotAllowedError') {
            // Autoplay was prevented by browser
            setNeedsInteraction(true);
            onPlayStateChange(false);
          } else {
            // Audio file might be missing (404) or unsupported, but don't stop the visual experience
            console.warn("Audio playback failed (file might be missing). Continuing visuals.", e);
          }
        });
      }
    } else {
      audio.pause();
    }
  }, [isPlaying, isMuted, trackIndex, onPlayStateChange]);

  const handleEnded = () => {
    if (playlist.length === 1) {
      audioRef.current?.play().catch(e => console.warn(e));
    } else {
      setTrackIndex(prev => (prev + 1) % playlist.length);
    }
  };

  const handleInitialInteraction = () => {
    setNeedsInteraction(false);
    onPlayStateChange(true);
  };

  return (
    <>
      <audio 
        ref={audioRef} 
        src={playlist[trackIndex]} 
        onEnded={handleEnded}
        playsInline 
      />
      
      {needsInteraction && (
        <div className={styles.interactionOverlay} onClick={handleInitialInteraction}>
          <p className={styles.interactionText}>Tap anywhere for sound</p>
        </div>
      )}

      {!needsInteraction && !hideControls && (
        <div className={styles.controls}>
          <button 
            className={styles.controlBtn} 
            onClick={() => onPlayStateChange(!isPlaying)}
            aria-label={isPlaying ? "Pause" : "Play"}
          >
            {isPlaying ? "Pause" : "Play"}
          </button>
          <button 
            className={styles.controlBtn} 
            onClick={() => onMuteStateChange(!isMuted)}
            aria-label={isMuted ? "Unmute" : "Mute"}
          >
            {isMuted ? "Unmute" : "Mute"}
          </button>
        </div>
      )}
    </>
  );
};
