export interface StoryScene {
  id: number;
  image: string;
  label: string;
  text: string;
  secondaryText: string;
  duration: number;
  composition: 'center-large' | 'left-text-right' | 'right-text-left' | 'full-dark' | 'layered' | 'slow-emerge' | 'typography-driven';
  transitionType: 'fade' | 'mask-reveal' | 'blur-focus' | 'slow-scale' | 'pan';
  cameraMotion: 'scale-up' | 'scale-down' | 'pan-left' | 'pan-right' | 'pan-up';
}

const photoModules = import.meta.glob('/public/photos/*.{png,jpg,jpeg,webp,gif,avif}', { eager: true, query: '?url' });
// Extract the actual URL generated by Vite
const photoPaths = Object.values(photoModules).map((mod: any) => mod.default as string);

const photos = photoPaths.length > 0 ? photoPaths : ["/photos/champ.png"]; // fallback if empty

const baseSentences = [
  { label: "A presence", text: "There are some people who change the atmosphere just by being there.", secondaryText: "" },
  { label: "Strength", text: "You carry a quiet strength.", secondaryText: "Even when things aren't easy." },
  { label: "Kindness", text: "And a kindness that people don't easily forget.", secondaryText: "" },
  { label: "Memories", text: "It’s in the small moments.", secondaryText: "The things you probably think no one notices." },
  { label: "", text: "But they are noticed.", secondaryText: "And they matter." },
  { label: "Time", text: "Another year passes.", secondaryText: "Another chapter opens." },
  { label: "The next chapter", text: "This one belongs entirely to you.", secondaryText: "" }
];

const compositions = ['center-large', 'left-text-right', 'right-text-left', 'layered', 'full-dark', 'slow-emerge', 'typography-driven'] as const;
const cameraMotions = ['scale-up', 'scale-down', 'pan-left', 'pan-right', 'pan-up'] as const;

export const storyData: StoryScene[] = photos.map((photoUrl, index) => {
  const sentence = baseSentences[index % baseSentences.length];
  
  return {
    id: index + 1,
    image: photoUrl,
    label: sentence.label,
    text: sentence.text,
    secondaryText: sentence.secondaryText,
    duration: 8500, // Fixed duration for smooth continuous flow
    composition: compositions[index % compositions.length],
    transitionType: 'fade',
    cameraMotion: cameraMotions[index % cameraMotions.length]
  };
});
